export const ADD_ERROR       ='ADD_ERROR'
export const REMOVE_ERROR    ='REMOVE_ERROR'
export const SET_CURRENT_USER='SET_CURRENT_USER'


export const LOAD_PRODUCTS   = "LOAD_PRODUCTS"
export const REMOVE_PRODUCTS = "REMOVE_PRODUCTS"
export const UPDATE_PRODUCTS = "UPDATE_PRODUCTS"

export const LOAD_ECOURSES   = "LOAD_ECOURSES"
export const REMOVE_ECOURSES = "REMOVE_ECOURSES"
export const UPDATE_ECOURSES = "UPDATE_ECOURSES"

export const LOAD_LESSONS   = "LOAD_LESSONS"
export const REMOVE_LESSONS = "REMOVE_LESSONS"
export const UPDATE_LESSONS = "UPDATE_LESSONS"